config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: shopping_dedup
      host: 10.141.14.145
      pass: password
      port: 6432
      schema: public
      threads: 8
      type: postgres
      user: postgres
  target: prod
