version: 2
sources:
- name: public
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_categories
  - name: _airbyte_raw_customers
  - name: _airbyte_raw_orderitems
  - name: _airbyte_raw_orders
  - name: _airbyte_raw_products
